version: "3.3"
services:
    flask_app:
        build: ./scripts
        ports:
            - "5000:8000"
    ui-app:
        build:
            context: ./ui-app
            args:
                nginx_config_file: default.local.conf
        ports:
            - "5001:80"
    
